name: Label pull request
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
